// <auto-generated />
using System;
using BE.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(HospitalManagementDbContext))]
    [Migration("20260604155922_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE.Model.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClinicId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ClinicId")
                        .HasName("PK_Clinic");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Clinic", (string)null);
                });

            modelBuilder.Entity("BE.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BEDADDDB927");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("BE.Model.Doctor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CommissionRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Doctors__1788CC4C38250ED5");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("BE.Model.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("CashierId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MedicalExaminationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoices__D796AAB5B4865AF0");

                    b.HasIndex("CashierId");

                    b.HasIndex("MedicalExaminationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BE.Model.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__InvoiceD__3214EC078829BCC8");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("BE.Model.MedicalExamination", b =>
                {
                    b.Property<int>("MedicalExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicalExaminationId"));

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CallCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Symptoms")
                        .HasColumnType("text");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TreatmentPlan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VisitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MedicalExaminationId")
                        .HasName("PK__MedicalE__60CB94EC9DB8D944");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalExaminations");
                });

            modelBuilder.Entity("BE.Model.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicationId"));

                    b.Property<decimal>("CurentPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Ingredient")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MedicationId")
                        .HasName("PK__Medicati__62EC1AFA1A13840B");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("BE.Model.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FamilyMedicalHistory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Patients__1788CC4CCDD88B0A");

                    b.HasIndex(new[] { "PatientCode" }, "UQ__Patients__B9C66DFED32204E5")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BE.Model.Payroll", b =>
                {
                    b.Property<int>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayrollId"));

                    b.Property<decimal?>("Allowances")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Bonuses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("Deductions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PayPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PayrollId")
                        .HasName("PK__Payrolls__99DFC67230D1A5E0");

                    b.HasIndex("StaffId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("BE.Model.Prescription", b =>
                {
                    b.Property<int>("PrescriptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrescriptionsId"));

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MedicalExaminationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PrescriptionsId")
                        .HasName("PK__Prescrip__A2F31069879F8761");

                    b.HasIndex("MedicalExaminationId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("BE.Model.PrescriptionDetail", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PrescriptionId", "MedicationId")
                        .HasName("PK__Prescrip__F63DC99D1532F43C");

                    b.HasIndex("MedicationId");

                    b.ToTable("PrescriptionDetails");
                });

            modelBuilder.Entity("BE.Model.Queue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QueueId"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MedicalExaminationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("QueueId")
                        .HasName("PK_Queue");

                    b.HasIndex("ClinicId");

                    b.HasIndex("MedicalExaminationId");

                    b.HasIndex("PatientId");

                    b.ToTable("Queue", (string)null);
                });

            modelBuilder.Entity("BE.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A1FFA2060");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BE.Model.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB00A3B1236B0");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BE.Model.ServiceDetail", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalExaminationId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ServiceId", "MedicalExaminationId")
                        .HasName("PK__ServiceD__131709449F09BC51");

                    b.HasIndex("MedicalExaminationId");

                    b.ToTable("ServiceDetails");
                });

            modelBuilder.Entity("BE.Model.Staff", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Staffs__1788CC4CE3829BDD");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "EmployeeCode" }, "UQ__Staffs__1F642548A20E1F16")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("BE.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C36FD5F7F");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BE.Model.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__UserRole__3214EC0724C9533F");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BE.Model.Clinic", b =>
                {
                    b.HasOne("BE.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Clinic_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BE.Model.Doctor", b =>
                {
                    b.HasOne("BE.Model.Staff", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("BE.Model.Doctor", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Doctors__UserId__3D5E1FD2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Model.Invoice", b =>
                {
                    b.HasOne("BE.Model.Staff", "Cashier")
                        .WithMany("Invoices")
                        .HasForeignKey("CashierId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__Cashie__628FA481");

                    b.HasOne("BE.Model.MedicalExamination", "MedicalExamination")
                        .WithMany("Invoices")
                        .HasForeignKey("MedicalExaminationId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__Medica__60A75C0F");

                    b.HasOne("BE.Model.Patient", "Patient")
                        .WithMany("Invoices")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__Patien__619B8048");

                    b.Navigation("Cashier");

                    b.Navigation("MedicalExamination");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BE.Model.InvoiceDetail", b =>
                {
                    b.HasOne("BE.Model.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceDe__Invoi__6754599E");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BE.Model.MedicalExamination", b =>
                {
                    b.HasOne("BE.Model.Clinic", "Clinic")
                        .WithMany("MedicalExaminations")
                        .HasForeignKey("ClinicId")
                        .HasConstraintName("FK_MedicalExamination_Clinic");

                    b.HasOne("BE.Model.Doctor", "Doctor")
                        .WithMany("MedicalExaminations")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalEx__Docto__46E78A0C");

                    b.HasOne("BE.Model.Patient", "Patient")
                        .WithMany("MedicalExaminations")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK__MedicalEx__Patie__45F365D3");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BE.Model.Patient", b =>
                {
                    b.HasOne("BE.Model.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("BE.Model.Patient", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Patients__UserId__35BCFE0A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Model.Payroll", b =>
                {
                    b.HasOne("BE.Model.Staff", "Staff")
                        .WithMany("Payrolls")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__Payrolls__StaffI__59FA5E80");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BE.Model.Prescription", b =>
                {
                    b.HasOne("BE.Model.MedicalExamination", "MedicalExamination")
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicalExaminationId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Medic__5165187F");

                    b.Navigation("MedicalExamination");
                });

            modelBuilder.Entity("BE.Model.PrescriptionDetail", b =>
                {
                    b.HasOne("BE.Model.Medication", "Medication")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicationId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Medic__571DF1D5");

                    b.HasOne("BE.Model.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Presc__5629CD9C");

                    b.Navigation("Medication");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("BE.Model.Queue", b =>
                {
                    b.HasOne("BE.Model.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .IsRequired()
                        .HasConstraintName("FK_Queue_Clinic");

                    b.HasOne("BE.Model.MedicalExamination", "MedicalExamination")
                        .WithMany()
                        .HasForeignKey("MedicalExaminationId")
                        .HasConstraintName("FK_Queue_MedicalExamination");

                    b.HasOne("BE.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Queue_Patient");

                    b.Navigation("Clinic");

                    b.Navigation("MedicalExamination");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BE.Model.ServiceDetail", b =>
                {
                    b.HasOne("BE.Model.MedicalExamination", "MedicalExamination")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("MedicalExaminationId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceDe__Medic__4D94879B");

                    b.HasOne("BE.Model.Service", "Service")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__ServiceDe__Servi__4CA06362");

                    b.Navigation("MedicalExamination");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BE.Model.Staff", b =>
                {
                    b.HasOne("BE.Model.Department", "Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Staffs__Departme__3A81B327");

                    b.HasOne("BE.Model.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("BE.Model.Staff", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Staffs__UserId__398D8EEE");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Model.UserRole", b =>
                {
                    b.HasOne("BE.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__RoleI__31EC6D26");

                    b.HasOne("BE.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__UserI__30F848ED");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Model.Clinic", b =>
                {
                    b.Navigation("MedicalExaminations");
                });

            modelBuilder.Entity("BE.Model.Department", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BE.Model.Doctor", b =>
                {
                    b.Navigation("MedicalExaminations");
                });

            modelBuilder.Entity("BE.Model.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("BE.Model.MedicalExamination", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Prescriptions");

                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("BE.Model.Medication", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("BE.Model.Patient", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("MedicalExaminations");
                });

            modelBuilder.Entity("BE.Model.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("BE.Model.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BE.Model.Service", b =>
                {
                    b.Navigation("ServiceDetails");
                });

            modelBuilder.Entity("BE.Model.Staff", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Invoices");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("BE.Model.User", b =>
                {
                    b.Navigation("Patient");

                    b.Navigation("Staff");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
